### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by spaar** [spaar/besiege-modloader#1]
Documentation is at http://spaar.github.io/besiege-modloader.
It still needs improvement, specifically more usage examples and there are some members that are missing all documentation too.

**Comment by spaar** [comment]
The new Mod attribute should also be properly documented.

**Comment by ZiMMy** [comment]
at least there should be a simple mod example that includes it

**Comment by spaar** [comment]
Yes. I will also update the mod tutorial on my Besiege Forums blog and put it into the repo as both guide and example.

**Comment by FeldrinH** [comment]
What sort of a documentation do you have in mind? A wiki, comments in the code, tutorials?

**Comment by L3tum** [comment]
Comments in the code are the first step. A wiki would be, currently, way too big for the few things that are able. Tutorials are better, like for generally modding.

**Comment by spaar** [comment]
As the API grows we'll also need to provide documentation for using it outside of the code. I'm thinking of using something like doxygen (or does .NET have built-in things like that?) to create a nice online documentation or something like that.

**Comment by L3tum** [comment]
I think .NET does have something like auto-generated docs, though I've never used them. I believe there are some plugins for Visual Studio as well.

**Comment by vissie003** [comment]
if you add 3 frontslashes ("///") just above the function, visual studio automatically generates a summary block, which gives you the ability to add documentation to the functions and will also be visible in Intellisense

**Comment by spaar** [comment]
I know that (and I think the other contributors as well), if you look into the code, there are quite a few functions that have documentation like that.
The question was more about exporting documentation like that to HTML or some other format for people to use without having to download the source code, but it appears that such software does indeed exist.

**Comment by vissie003** [comment]
I found this:

http://shfb.codeplex.com/

Did a quick test, it automatically generates HTML Files.

**Comment by spaar** [comment]
Yeah, Sandcastle is a name I heard in that context as well.
I'll take a look at setting something like this up, maybe using GitHub pages for hosting it.

**Comment by vissie003** [comment]
Tomorrow it is sunday, so if there is some stuff to do, just say it :-)

**Comment by spaar** [comment]
If you would like to try generating some nice documentation from the source, go right ahead :) I'll gladly take the help.

**Comment by spaar** [comment]
Okay, so documentation largely exists now. I documented every public member in the code and wrote some introduction as well. Ideally, I'd still like to create kind of a guide to the API but I don't really think that it's big enough to warrant that at the moment.
Now we just need to actually host the documentation somewhere.

**Comment by vissie003** [comment]
It is possible to host pages on Google Drive:

https://support.google.com/drive/answer/2881970?hl=en

**Comment by spaar** [comment]
That's also an option.
However, I'll hold of on doing anything about hosting this until I make a decision about what to do regarding the situation with Vapid's Mod Loader and this one.

**Comment by spaar** [comment]
Quick update: Documentation is hosted on GitHub pages now, via the gh-pages branch here. URL: http://spaar.github.io/besiege-modloader.
That means hosting and generation of the documentation is mostly sorted, this issue is now about adding more documentation. Specifically, more usage examples and also documentations for items that don't have any at all yet.

**Comment by spaar** [comment]
Closing this, the mod loader will not receive future updates as it was superseded by the official in-game one.
