### ISSUE TITLE
ArgumentNullException in Keys.cs

### ISSUE THREAD

**Issue by ZiMMy** [spaar/besiege-modloader#10]
[Exception] ArgumentNullException: Argument cannot be null.
Parameter name: value
System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase)
System.Enum.Parse (System.Type enumType, System.String value)
spaar.Keys.getKey (System.String keyName)
spaar.KeySettings.Update ()

**Comment by spaar** [comment]
I'll look into this.

**Comment by spaar** [comment]
Can you give additional info on what you did? I can get similiar exceptions by storing invalid data in the Keys.txt file, which should be fixed as well. Not this specific one though.

**Comment by ZiMMy** [comment]
I did nothing actually. I start the game, open the console and see all those exceptions.

My Keys.txt:

ConsoleK1=LeftControl
ConsoleK2=K
OEK1=LeftControl
OEK2=O
ConfigurateK1=LeftControl
ConfigurateK2=L

**Comment by spaar** [comment]
Ah, I see. That Keys.txt was generated by a version where the settings dialog was still named Configurate. The last two lines should be

```
SettingsK1=LeftControl
SettingsK2=L
```

That also explains how to reproduce the exception: Not by having invalid values but by missing some keys. Error handling should definetely be improved here.

**Comment by ZiMMy** [comment]
Really. Well, setting default values function when unable to get them from the config have to be made definitely.
