### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by ZiMMy** [spaar/besiege-modloader#14]
- [x] Put every class (even the tiny ones) into separate files.
- [ ] Extract large pieces of code from functions like Start(), Update() etc into different separate methods.

Thus the code will be easier to modify, document and understand, especially for other modders.

**Comment by spaar** [comment]
I generally agree. The only thing I'm not sure about is every class in its own file. I see why this is a good idea in nearly all cases but would you really give, for example IGameStateObserver its own file? I think it's reasonable to leave it together with GameObserver, what do you think?

**Comment by ZiMMy** [comment]
IGameStateObserver is an interface, though.
Well, those two can be left together until (unless) they become larger.

**Comment by spaar** [comment]
I guess so ^^ I mainly took it as an example for a very tiny... thing.
I agree, if they become larger they should be seperated.

**Comment by ZiMMy** [comment]
And BTW what are you going to do with the configuration module? Continue developing from here on or revert to 3482e68b46c136a338a93af0e92385d97a6ecec3 ?

**Comment by spaar** [comment]
I'm mostly likely going to revert and then re-create any other changes that have been made since then. I'll wait till tomorrow though, give Letum a chance to explain his reasoning a bit more.

**Comment by spaar** [comment]
Closing this, it was in largely achieved with merging 'overhaul'.
