### ISSUE TITLE
Console Improvement and commands

### ISSUE THREAD

**Issue by L3tum** [spaar/besiege-modloader#21]
Make the console better(e.g. that you can choose if you want to display exceptions or only warning or such) and enabling modders the abilty to implement an attribute to which they can assign a name and so on and you can call it through the console

**Comment by L3tum** [comment]
Can't assign myself :C However, I just opened that to let you know that I'm doing that^^

**Comment by spaar** [comment]
The filtering part is already part of #2, but the custom console commands certainly deserve their own issue.

**Comment by L3tum** [comment]
Oh,ok, haven't seen that... Thanks^^

**Comment by spaar** [comment]
Closing this, as commands are implemented now, as well as filtering.
