### ISSUE TITLE
ModLoader.AddPiece not being set

### ISSUE THREAD

**Issue by spaar** [spaar/besiege-modloader#25]
After moving setting the AddPiece reference from the object explorer to ModLoader, it is never being set at all.
Unfortunately the game object the mod loader is attached to is destroyed when exiting the main menu and the mod loader with it, ensuring that the search for AddPiece never succeeds as that is only created after that.
There would be multiple ways to fix this:
- Create a new bootstrapper class that creates the mod loader lord object and attaches the mod loader to it and make InternalModLoader attach that instead of the mod loader.
- Make the mod loader only create the game object the first time it is created and then attach another instance of itself to that. The second mod loader would do everything else and also persist between level changes.
- Make InternalModLoader create the mod loader lord game object and attach the mod loader to that.

There are probably other ways as well, what do you think would be the best way to handle this?

**Comment by L3tum** [comment]
I would be for the 3rd idea, because 1) needs a new class and more to load, 2) it probably difficult to load and could lead to bugs. I haven't followed the commits for some time, so why did you move it into the mod loader?

**Comment by spaar** [comment]
3rd sounds good.
That was some time ago actually, when the object explorer was completely excluded from non-developer builds. That's why it can't be set there anymore.

**Comment by L3tum** [comment]
Oh yeah, sorry.... What about making an own AddPiece class?

**Comment by spaar** [comment]
I think that's kind of overkill

**Comment by L3tum** [comment]
^^ Ok

**Comment by spaar** [comment]
Alright, fixed.
