### ISSUE TITLE
Support for adding custom block types

### ISSUE THREAD

**Issue by FeldrinH** [spaar/besiege-modloader#33]
I was just wondering what are your plans for adding support for adding custom block types to the game.
Have you looked into it?

**Comment by L3tum** [comment]
@spaar Was looking into creating custom blocks and I think he already had some code going, but it's not something very easy and we're currently making an overhaul of the modloader, so tbh this won't be the first thing on the list^^

**Comment by spaar** [comment]
@L3tum Is correct. I've done some work on this, although seperate from the mod loader. Currenlty I can basically add a new type to the game, however actually creating a type to add proves kind of difficult. Especially the way connections are formed is sort of difficult to understand and replicate in a completely new block.
Once I get this working, I will definitely try to add a nice API to the mod loader for this as well. But I will concentrate on other work for now, see the overhaul branch for some examples of that.

**Comment by spaar** [comment]
This was achieved, not in the mod loader but with TheGuysYouDespise's block loader. Closing.
