### ISSUE TITLE
Installer error-handling

### ISSUE THREAD

**Issue by spaar** [spaar/besiege-modloader#36]
The installer needs much more robust error handling, it's quite prone to uncatched exceptions currently.

**Comment by rhkddn1216** [comment]
greetings. I tried to install your modloader, but it doesn't and shows me a error message : Can't load file(or assembly) supposed to subject in here. 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
I've tried to install manually(not via installer), it failed also. I guess this problem is something about 64bits. If you can solve this one or know something, reply please.

**Comment by L3tum** [comment]
@rhkddn1216 What do you mean it "failed" when you tried to install it manually?

**Comment by spaar** [comment]
@rhkddn1216 Try installing the .NET framework version 4 or higher. That should only be needed for the installer though, if you install it manually it should work even without that. I also don't think it has anything to do with 64bits, considering it works perfectly fine on a lot of other 64-bit systems.

**Comment by rhkddn1216** [comment]
Oh Thx I didn't know you've replied.
At first, actually. It works. But some mods that compatible with modloader
before I upgrade Besiege's version, now incompatible.(it was 0.11
previously, now 0.25)
I wonder it happens frequently, or make sense(with version).

2016-02-16 0:16 GMT+09:00 spaar notifications@github.com:

**Comment by rhkddn1216** [comment]
Incompatible mods for example, MultiMod for 0.20, rocketmod for 0.20, and
else for 0.20 usually. As I said, modloader and that mods DID installed
manually, yes.
Hope you reply, and Thanks again.

2016-02-19 20:02 GMT+09:00 신광우 rhkddn1216@gmail.com:

**Comment by L3tum** [comment]
@rhkddn1216 Incompatible mods can happen quite often, especially for mods that are this far behind in Besiege versions.

**Comment by spaar** [comment]
Basically, what @L3tum said. I try to avoid any mod-breaking changes in the mod loader itself (so far there was only the 0.x.x -> 1.x.x transition) but the code and organisation of the game itself can change (sometimes quite dramatically) between updates, which is what breaks some mods.

**Comment by rhkddn1216** [comment]
OK. Got it. Thanks for your kindness. BTW, Is there any solution about this? I mean, reinstall the game, for example... Or format my desktop even, at any costs.

나의 iPhone에서 보냄
1. 2. 20. 오전 2:23 spaar notifications@github.com 작성:

**Comment by spaar** [comment]
The only solution for mods that aren't compatible with new Besiege versions is that the authors (or sometimes someone else) updates the mods.

**Comment by rhkddn1216** [comment]
It sounds miserable. Thank you anyway.

나의 iPhone에서 보냄
1. 2. 21. 오후 9:49 spaar notifications@github.com 작성:
