### ISSUE TITLE
it wont work.

### ISSUE THREAD

**Issue by bleachrocks7** [spaar/besiege-modloader#40]
i have tried about 5 times to load up the modloader, mods, and looked all over the internet on why this is not working. I downloaded the .exe file, ran it and used the newest version, it comes up with error loading mods, then it tells me its done an I can start the game. its like I did nothing an the game runs as does with out any mods, wtf im getting really mad at this point.

**Comment by spaar** [comment]
I assume that you mean the installer with .exe file, right?
If so, can you give me the full error message it gives you?

(The message that it's done is misleading though, that's totally right. I think it gives that no matter whether or not there were errors, I'll look into changing that.)

**Comment by bleachrocks7** [comment]
thank you for looking at this. yes its the .exe file that used an I have done everything it said on the forum. what happens is that once I start the installer it comes up with "error installing the mod loader" then right after I close that window another window comes up saying, "done, you can close the installer and start besiege"

do I have to download the mods later? I had done this all way back when flamethrowers were a big thing with modding, I had a hard time with that as well but I got it then. I really don't know what to do an I am sorry for my lack on knowledge.

**Comment by spaar** [comment]
Hm, I'm afraid I don't really know why it isn't working. I'll add more helpful error messages to the installer in the future that would hopefully help with figuring something like this out, but right now that's not of much use.

Can you try doing a manual installation instead of using the installer? It's not that difficult, the instructions are in the forum post.

**Comment by bleachrocks7** [comment]
im reading into how to do it manually right now, im trying to replace the AUS.DLL file for the loader. im not all the computer smart so im sorry im being a pain lol

**Comment by spaar** [comment]
If you need help with the manual installation, I'm happy to answer your questions. I'd need some more information though, not just that you're trying to replace the file, but what exactly you're having a problem with.

Also, did you mean to close the issue or was that by accident? If it was by accident, you can just reopen it.

**Comment by bleachrocks7** [comment]
lol wrong button my bad, if I come along with any other issues ill post them on here, I cant thank you enough for just reading an taking the time to help me.

**Comment by bleachrocks7** [comment]
so if all is good now, just installing the loader wont do anything else right? I tried putting editorplus into the mods folder but it still isn't working, I loaded up the game an it started no problem but there isn't any indicator for the mod options?

**Comment by spaar** [comment]
You can check if the loader is installed correctly by pressing Ctrl+K, if that opens the console then everything is installed correctly.
Editor+ is outdated and doesn't work with the newest Besiege versions anymore I'm afraid, try using Building Tools by TheGuysYouDespise as an alternative.

**Comment by bleachrocks7** [comment]
I just tried the ctrl+k in game an nothing happened lol, back to square one I guess

**Comment by spaar** [comment]
Can you upload the output_log.txt file located in the Besiege_Data folder?

**Comment by bleachrocks7** [comment]
[output_log.txt](https://github.com/spaar/besiege-modloader/files/196213/output_log.txt)

like that? or do I have to do something else? I really am sorry for how much I don't know about computers =[

**Comment by bleachrocks7** [comment]
it seems that the only thing I can not do is replace the AUS.DLL file, all it says is that I need permission to change it, I don't know how to change to admin to do said replacements

**Comment by spaar** [comment]
Ah, you either need to get yourself admin rights (you can try right-clicking the installer and choosing "Run as Administrator", alternatively the Windows Explorer should offer you to try again with admin rights if you need more permissions). If you can't get admin rights on your computer, you can try installing Besiege to a different location where you have permissions to change the files.

**Comment by bleachrocks7** [comment]
ive been tinkering over this for 16 hours now, ive had my fill an now im an asshole, im done with all of this for quite a long time, I really appreciate all of your help but I cant stand to do anything else, im about an inch away from throwing my computer off a bridge...

**Comment by Da0neDatGotAway** [comment]
Hi I had this problem to

**Comment by Dushess** [comment]
This modloader is part of the game now, use steam workshop for mods.
