### ISSUE TITLE
Issue appon loading besiege

### ISSUE THREAD

**Issue by dsih01** [spaar/besiege-modloader#41]
installed the modloader after having it for 0.27 and this happened, it also happened on a newly downloaded besiege game

![problem](https://cloud.githubusercontent.com/assets/19808442/15878288/e288eae6-2cd6-11e6-8380-89eaec4b1c4c.jpg)

**Comment by spaar** [comment]
Can you tell me how exactly you installed it? Using the installer or the manual installation?

**Comment by spaar** [comment]
Closing this as I didn't receive any further information, re-open it if you still need assistance.
