### ISSUE TITLE
I'm expiriencing some problems

### ISSUE THREAD

**Issue by AsgarLoke** [spaar/besiege-modloader#42]
![screen shot 2016-06-19 at 23 16 13](https://cloud.githubusercontent.com/assets/20031888/16179879/f73e62a8-3673-11e6-8d09-54d1414ddab5.png)
I have followed every single step in the ios guide (Mac Guide) and understood every single step as i have a lot of expirience in mac computers. Somehow when i open besiege all text and instructions in the game is displayed (for an example all the blocks in the hotbar is displayed as in use and the text for the different categories of blocks text overlaps eachother)  in the same time and only very few controls are working such as rolling the camera angle and zooming. Have you got any idea if the new update have something to do with it? or did i do something wrong (pretty unlikely) Thank you in advance.

**Comment by spaar** [comment]
That's an odd error. Can you upload your log file? It's either named output_log.txt or Player.log, I forgot which one it is on Mac.

**Comment by spaar** [comment]
Closing this as I didn't receive any further information, re-open it if you still need assistance.
