### ISSUE TITLE
I'm experiencing console issues.

### ISSUE THREAD

**Issue by MoosCrebolder** [spaar/besiege-modloader#43]
Hey man love your work but I'm experiencing some problems. I'm not a very techy person and I use a mac so I'm afraid you'll have to give me detailed instructions if you want to help out. I installed your mod loader along with the antigravity mod on the steam version of Besiege, which works fine except the mod's GUI is constantly there which is annoying so I tried ToggleGUI in the modloader console (I found this command on the mod's page) but I can't seem to activate the command by pressing return or any other key. I assume that I'm just doing something wrong but I can't figure out what it is. I can't use any other commands either (I tried "help" and "enableMod"). If I have to share my log or anything just tell me but I have the feeling that I'm just doing something stupid. Thanks in advance.

**Comment by L3tum** [comment]
What happens when you press Enter(or the respective key on Mac) after inputting a command? Like, does nothing happen at all, or is some kind of error printed to the console?
Furthermore, I don't know for sure but I suspect the mod to be outdated, as the last time ITR edited the post was on the 18th October of 2015, but I'll message him and ask him in that matter.

**Comment by MoosCrebolder** [comment]
When I press enter nothing happens. The command doesn't change at all. It could very well be that the mod is outdated but besides this issue, it functions just fine. Thanks for your input man.

**Comment by spaar** [comment]
Can you try replacing your SpaarModLoader.dll file with the [one in this download](https://github.com/spaar/besiege-modloader/files/327851/SpaarModLoader.zip) and then try a command (preferably a built-in one like `help`) again?

**Comment by MoosCrebolder** [comment]
I have no idea how but that worked perfectly. Thanks for your help man!
