### ISSUE TITLE
Problem with modloader

### ISSUE THREAD

**Issue by Sathans** [spaar/besiege-modloader#44]
![screenshot 2](https://cloud.githubusercontent.com/assets/16865809/16758694/779a84b2-4813-11e6-8cb2-4cbe355836bb.jpg)

Can't do anything after I installed the mod loader v0.3.1

**Comment by ghost** [comment]
V0.3.1 is an old version that is not compatible with the latest game version.

**Comment by spaar** [comment]
@SamKeightley is correct, try installing the current version 1.4.1 instead.

**Comment by spaar** [comment]
Since there's no feedback, I'm closing this issue. Re-open it if you need further assistance.
