### ISSUE TITLE
OSX beachball of death after installing modloader

### ISSUE THREAD

**Issue by cdupras** [spaar/besiege-modloader#45]
I'm running Besiege via Steam on OSX, and followed the modloader's steam install instructions. I have not installed any other mods (yet).

When I launch Besiege from Steam, the Besiege window appears, blank, with a beachball of death. After 2 minutes, the Besiege window disappears and is no longer running. HALP!

Versions:
Steam: Aug 23 2016
Besiege: 0.32 (always up to date via Steam)
Spaar's Modloader: 1.5.1

**Comment by spaar** [comment]
I just released an update, can you try with that again?
If it still doesn't work, can you post the Player.log file from ~/Library/Logs/Unity/ please?

**Comment by spaar** [comment]
Closing this since there's no response yet. Re-open if it's still a problem.
