### ISSUE TITLE
Embedded Block Loader

### ISSUE THREAD

**Issue by OldWorldShade** [spaar/besiege-modloader#49]
I have Windows 8.1, Besiege v0.4, and spaars Mod loader 1.5.4 and the block mods I have aren't working with your embedded block loader. is this supposed to happen or is this an actual issue?
Mods: Cloud and Ground, Advanced Laser, Tank Tracks, suRails, Besiege Edit, More Blocks, and i think thats it.

**Comment by spaar** [comment]
I'm afraid most of the mods you're trying to use aren't being kept up-to-date by their creators anymore. Try seeing in their forum threads which ones are actually compatible with the current Besiege version and remove all others. That should hopefully fix it.
