### ISSUE TITLE
Harmony

### ISSUE THREAD

**Issue by pardeike** [spaar/besiege-modloader#55]
This needs to be updated to Harmony 1.0.9 which simplifies platform specific code and thus works with Linux. Cheers, big fan on Besiege btw.

**Comment by spaar** [comment]
Thanks for the heads-up, glad you like what we're doing :)

PS: The closing&re-opening was a mis-click, sorry about that.

**Comment by pardeike** [comment]
One day if I have time I'll look into how you use my library with Besiege. /Andreas
