### ISSUE TITLE
modloader's Windows Installer reporting an error while installing

### ISSUE THREAD

**Issue by jackhalfey** [spaar/besiege-modloader#56]
Hi, I'm having a problem where when I try to use the ModLoader Installer.exe I get an error message a second or so after pressing "install." I'm on Windows 10 attempting to install the 1.7.0 version of the modloader onto Besiege v0.45, with no mods installed. I've tried both the normal and developer edition, neither work. Is there something I can do to fix this, or should I try the manual installation detailed on the game forums? (I'm a bit leery about messing with the game files.) Here's a picture of the error message: http://i.imgur.com/m0K2rsz.jpg

**Comment by spaar** [comment]
Try running the installer as administrator or make sure it has permissions to modify the game files without it.
Alternatively, the manual installation isn't that difficult either, and having the game on Steam means it's never particularly difficult to get back to a working game if you break something by accident.

Sorry about the rather unhelpful error message btw, that's one thing that definitely still needs improvement.
