### ISSUE TITLE
I don't have Assembly-UnityScript.dll in my Data folder (Mac)

### ISSUE THREAD

**Issue by Draaken** [spaar/besiege-modloader#57]
Hi, I 'm on Mac OSX El Capitan 10.11.6 and Besiege 0.45. I've downloaded the mod loader folder and when I go in Besiege/Contents/Resources/Data/Managed they are just a folder caled "etc". And when I copy Assembly-UnityScript.dll from the spaar's Mod Loader folder and run the game, the mod loader is not activated (nothing appened whe I do ctrl+k or cmd+k).

**Comment by spaar** [comment]
That sounds like you looked in Besiege/Contents/Data/Managed, not Besiege/Contents/**Resources**/Data/Managed. The paths are very similiar, but the difference is important.

**Comment by Draaken** [comment]
I made a mistake ^^', I looked in Besiege/Contents/Data/Managed and not in Besiege/Contents/Resources/Data/Managed. In Besiege/Contents/Data/Managed I have that: 
![capture d ecran 2017-04-21 a 16 02 01](https://cloud.githubusercontent.com/assets/27855495/25280927/e7ebab3e-26ab-11e7-9918-6c18f4461007.png)

**Comment by spaar** [comment]
Ok, so did you manage to install it now?

**Comment by Draaken** [comment]
Yes, and that didn't work, but I searched "managed" in Data folder with the search bar and I found an other folder, where there are Assembly-UnityScript.dll. After, I did the normal installation and the mod loader work. But I don't know were are this managed folder... it's strange.

**Comment by spaar** [comment]
Good to hear you managed to make it work.
