### ISSUE TITLE
it wont work

### ISSUE THREAD

**Issue by jlooney2004** [spaar/besiege-modloader#58]
So, I used the mac download, and finder did not ask to replace Assembly-UnityScript.dll, I did everything else, it went smoothly, so I downloaded NoBounds and EasyScale, and put them in the mods folder. I ran the game, and it ran like vanilla. please tell me if i didn't supply enough info.

Please help! :)

**Comment by spaar** [comment]
If it didn't ask you if you want to replace the file, you probably put it into the wrong folder. You **need** to put it in the folder where there already is an Assembly-UnityScript.dll file in the vanilla game and replace that. That's "Besiege/Contents/**Resources**/Data/Managed". There is also a Besiege/Contents/Data/Managed folder but that won't work.

**Comment by jlooney2004** [comment]
oh, that might be it, thanks! sorry for the trouble
