### ISSUE TITLE
Spaar mod loader not loading on linux

### ISSUE THREAD

**Issue by FishtoastSci** [spaar/besiege-modloader#59]
I'm running into an issue with the spaar mod loader on Ubuntu Linux. as of current i am using Ubuntu 16.04 have v 0.45 of besiege from steam and the 1.7.0 developer version of spaar's mod loader
the problem I am having is that spaar does not load at all which is odd because I had spaar properly installed and running mods only a few weeks prior I have reinstalled besiege and mod loader numerous time as well as loaded it with out any mods installed. i can provide more info if needed. and any help is appreciated

**Comment by spaar** [comment]
Can you attach your log file? It's called `Player.log` and located in `~/.config/unity3d/Spiderling Games/Besiege/` on Linux IIRC.

**Comment by FishtoastSci** [comment]
here is my log form the last time i booted the game (today the 12th of may)
[playerlog.txt](https://github.com/spaar/besiege-modloader/files/998311/playerlog.txt)

**Comment by spaar** [comment]
Something seems to be going wrong when the mod loader tries to load the configuration file. Try replacing SpaarModLoader.dll in Besiege_Data/Mods/ with the file in the attached zip file, run the game again and upload the Player.log file again, it should then contain some more debug information.

[SpaarModLoader.zip](https://github.com/spaar/besiege-modloader/files/998664/SpaarModLoader.zip)

**Comment by FishtoastSci** [comment]
[playerlog.txt](https://github.com/spaar/besiege-modloader/files/998982/playerlog.txt)
heres the new one after installing the new dll file

**Comment by spaar** [comment]
It looks like the configuration file for the Enhanced Camera mod somehow broke, I'm not sure how that happened. Try deleting that or alternatively using the mod loader version attached to this post. It contains some additional error-handling for configuration loading that will also be present in the next release.

[SpaarModLoader.zip](https://github.com/spaar/besiege-modloader/files/999445/SpaarModLoader.zip)

**Comment by FishtoastSci** [comment]
alright it would appear that everything is in order the mods have loaded correctly thank you

**Comment by spaar** [comment]
Good to hear that, thanks for reporting the bug.
