### ISSUE TITLE
error on windows

### ISSUE THREAD

**Issue by jeremyswe** [spaar/besiege-modloader#60]
so i downloaded the file and runit but ther is an error that reads HKLM/Software/Microsoft/.NETFramework/Installroot. swedish words för att peka på installationsplatsen för .NET Framework. some body plz help me :)

**Comment by spaar** [comment]
Apparently you don't have the .NET framework installed or the installation is somehow broken (probably more likely, Windows has been including the framework by default for quite a while now). You can try fixing the installation by setting the registry key mentioned in the error message to the location of the framework, if you know what you're doing. If you don't know how to do that, try re-installing the framework using the [installer by Microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=55170).
