### ISSUE TITLE
Modloader not working on mac IOS

### ISSUE THREAD

**Issue by theactualjessey** [spaar/besiege-modloader#61]
When i did all the steps for the Modloader on mac (steam version), I ran besiege and I didn't know how to find the modloader or where it was. Is there something wrong with the modloader for the steam version on Mac at this time or is it just me?

**Comment by spaar** [comment]
The mod loader should work fine on macOS.
To test if it works for you, press Ctrl+K (or Cmd+K) and see if the mod loader console opens up.

**Comment by theactualjessey** [comment]
the console doesn't show up when i try it, and I'm pretty sure I've done all of the steps correctly.

**Comment by spaar** [comment]
Can you open and close Besiege again and then post the Player.log file that's in `~/Library/Logs/Unity/` please?

**Comment by theactualjessey** [comment]
I sent the file by Email

**Comment by spaar** [comment]
Uhm, where exactly did you send it? I don't seem to have gotten an email.
You can just upload the file here  by dragging & dropping it onto the text box.

**Comment by theactualjessey** [comment]
I tried, it says that they don't support the file type. Any other way I can send it to you?

**Comment by spaar** [comment]
Just rename it from Player.log to Player.txt and upload it here.

**Comment by theactualjessey** [comment]
[Player.txt](https://github.com/spaar/besiege-modloader/files/1236799/Player.txt)

**Comment by spaar** [comment]
The mod loader's .dll file is never loaded apparently. Are you sure you correctly replaced the Assembly-UnityScript.dll file in `/Users/Jesseywd/Library/Application Support/Steam/steamapps/common/Besiege/Besiege.app/Contents/Resources/Data/Managed/` with the one from the mod loader download?

**Comment by theactualjessey** [comment]
I'm pretty sure I did that. Is it maybe because i used a different Assembly-UnityScript.dll file from a different folder? I lost the dll file that was in the original folder where all the other files were.

**Comment by theactualjessey** [comment]
Also, I downloaded the mod loader labeled The Normal Mod Loader from the website.

**Comment by spaar** [comment]
Normal Mod Loader would be correct for you.
Can you go into your Contents/Resources/Data/Managed/ and upload the Assembly-UnityScript.dll file here? (Just rename it to any of the supported file types, I'll know to rename it then)

**Comment by theactualjessey** [comment]
[Assembly-UnityScript.txt](https://github.com/spaar/besiege-modloader/files/1245191/Assembly-UnityScript.txt)

**Comment by spaar** [comment]
Hm, this is weird. That seems to be the correct file. Try using the "Verify integrity of game files" option in Steam and then re-do the mod loader installation process, taking special care that you do in fact _replace_ the Assembly-UnityScript.dll file that is there by default.

**Comment by theactualjessey** [comment]
I verified the files and it said that one file wasn't verified so i checked back but the mod still doesn't work. The weird thing is that when I first downloaded the mod loader and put the dll file in the game files, there was no 'Replace' option. I replaced the new dll file with another dll file from a different folder because I wanted to make sure.

**Comment by spaar** [comment]
> I replaced the new dll file with another dll file from a different folder because I wanted to make sure.

I'm a bit confused by this. Are you sure that ultimately the Assembly-UnityScript.dll file from the mod loader was in the location where the original game file used to be?

**Comment by theactualjessey** [comment]
When I first put the Assembly-UnityScript.dll file in the correct folder, there was't a replace option because the original dll file didn't seem to be in there. So I put the Assembly-UnityScript.dll file in the folder and it didn't give me a replace option so I replaced it (the file from the mod loader) with another Assembly-UnityScript.dll  from a different zip file because I was kind of confused and I thought the file was broken. 
Just to make sure, I put the Assembly-UnityScript.dll into contents-data-managed.

**Comment by spaar** [comment]
If you put it into a folder that didn't originally have it, that's why it doesn't work.
> I put the Assembly-UnityScript.dll into contents-data-managed

That's probably the problem, it should be Contents/**Resources**/Data/Managed I believe.

**Comment by theactualjessey** [comment]
ahhh I think that solved that problem, although the console still doesn't show up. On the website it says that i have to put the Mods file in Besiege/Besiege_Data but I don't know how to there.

**Comment by spaar** [comment]
Besiege/Besiege_Data is the path on Windows and Linux. The folder structure on macOS is a bit different, so make sure to read the instructions carefully.

**Comment by spaar** [comment]
Closing this after no further feedback.
