### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GhostShot3** [spaar/besiege-modloader#62]
"Error installing the mod loader"
Plataform : Steam windowns 10

**Comment by spaar** [comment]
If you are using the newest version of the installer, it should give you an option to copy more information to the clipboard. Do that and then post that here.
Before you do that though, also try running the installer as administrator. The most common error is that the installer just doesn't have permission to modify the game files. The newest version of the installer should (ideally) handle this a bit more gracefully, but it sounds like you might be using a slightly older version.

**Comment by GhostShot3** [comment]
The error
```
Could not find file 'F:\Steam\steamapps\common\Besiege\Besiege_Data\Managed\Assembly-UnityScript.dll'.:
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   em spaar.ModLoader.Installer.Installer.InstallModLoader(String besiegeLocation, ModLoaderVersion version, Boolean developer)
   em spaar.ModLoader.Installer.FormInstaller.btnInstall_Click(Object sender, EventArgs e)
```
I tried to run with adminstrator mode and even with the compartment and still the error persists.

**Comment by spaar** [comment]
Make sure that your Besiege installation actually is at `F:\Steam\steamapps\common\Besiege\` and correct the path in the text box if it's not.
If the error still occurs after that, use the "Verify game files" option on Besiege in Steam and then try running the installer again (as admin).
If it still throws an error after that, check if it's still the same one and post again here.

**Comment by GhostShot3** [comment]
Fixed it
