### ISSUE TITLE
Istaller not working

### ISSUE THREAD

**Issue by GhostShot3** [spaar/besiege-modloader#64]
I tried to use the installer and it did not install, I know this because i tried to put several mod and they did not work.

Besiege version : Lastest
Plataform : Steam

**Comment by floatflower** [comment]
Neither do I, I use v1.7.1 mod loader installer and on Besiege v0.60.0-6437 with Steam. After installing, I opened Besiege and pressed Ctrl+M, it did not show anything.

**Comment by lenartbezek** [comment]
Mod loader does not work with Besiege v0.60. Watch this repository and wait for updates. It will take some time as the changes to the game were pretty big.

**Comment by spaar** [comment]
See #65.
