### ISSUE TITLE
Multiverse Update

### ISSUE THREAD

**Issue by spaar** [spaar/besiege-modloader#65]
The mod loader does not currently support Besiege v0.60 (aka the Multiverse update).

The game internals changed a lot with the update and it's not possible right now to give a timeframe for when the mod loader will be updated.

If you are fine with a limited selection of mods, ITR's PostPlace, NoBounds and ColliderDisplay as well as Lench's EasyScale mods are available in a "discount" form that may be limited in features but works in v0.60.
Take a look at [temporary mods for 0.60](http://forum.spiderlinggames.co.uk/index.php?threads/temporary-mods-for-0-6.6479/). Do not expect these mods to always work correctly in multiplayer.

Otherwise, there is a workaround for those who can't live without their mods:
1. In Steam, right-click Besiege, select Properties and go to the Beta tab. Choose the `previousbuild` beta.
2. After Steam downloads the game again, make a copy of the Besiege directory in your Steam library (`steamapps/common/Besiege`).
3. In Steam, deselect the `previousbuild` branch again and let Steam redownload the current version of the game.
4. You now have both v0.45 and v0.60 installed. You can install any mods you need back into the v0.45 install. If you want to, you can also add v0.45 into your Steam library (as a non-Steam game) so you can easily launch either one from Steam.
5. If you also want support for the Steam workshop in your v0.45 installation, place this [steam_appid.txt](https://github.com/spaar/besiege-modloader/files/1587327/steam_appid.txt) file in the Besiege directory, next to Besiege.exe.

Thank you for your patience while the mod loader is being updated.

**Comment by Dushess** [comment]
Maybe important note about this method. If link another instance as non-steam game, it will not have access to skins.

**Comment by GhostShot3** [comment]
Ok this will be fixed when ?

**Comment by nihaals** [comment]
>it's not possible right now to give a timeframe for when the mod loader will be updated

You should read the comment before replying.

**Comment by spaar** [comment]
> Maybe important note about this method. If link another instance as non-steam game, it will not have access to skins.

If you place the attached file in the root Besiege directory (next to Besiege.exe), Steam support should also work correctly I believe. I'll mention it in the main post.

[steam_appid.txt](https://github.com/spaar/besiege-modloader/files/1587322/steam_appid.txt)

**Comment by Dushess** [comment]
Oh yes, definately, steam just don't know, that it's his own game without that file. Thanks.
Actually, you mean Steam Community module.

Also plugin manager won't work.

**Comment by Lecord** [comment]
I  need your help,sorry if my english is bad but when i change the size of blocks(easy escale mod),and save it when i load the blocks are on default size,same when i upload something to workshop

Please,help.
i have the multiverse update.
![fail](https://user-images.githubusercontent.com/35670942/35200023-9c83f724-fee5-11e7-8e69-fad81400b419.png)

**Comment by spaar** [comment]
@Lecord Since you're using the Multiverse update and this mod loader doesn't currently work with Multiverse, your issue can't be related to the mod loader. Please ask on the forum thread of EasyScale for EasyScale-specific problems.

**Comment by Lecord** [comment]
@spaar Thank you.

**Comment by vorticus** [comment]
sorry what you mean make a copy of besiege directory again

**Comment by spaar** [comment]
@vorticus When you have the previousbuild beta installed, you can just use the file explorer to go to the Besiege folder and make a copy of it, like with any other folder on your computer. When you saved that somewhere else, you can go back to the current version in Steam, but the copy you made will still work and be the previousbuild, so you can install the mod loader on that.

**Comment by vorticus** [comment]
@spaar  thanks is solved :)

**Comment by vorticus** [comment]
yay  i dont have to keep reinstalling 👍 👍

**Comment by vorticus** [comment]
@spaar  wait i'm sorry one more problem , i cannot use shift + tab combination in-game on PrevBuild

**Comment by spaar** [comment]
@vorticus Sorry if I'M missing something here, but what do you expect shift+tab to do?

**Comment by Dushess** [comment]
https://steamcommunity.com/games/346010/announcements/detail/1663398418937409700

**Comment by spaar** [comment]
Indeed :)

As written in the announcement above, the game is going to get official mod support in the future. This consequently means that this mod loader is not going to be updated for Multiverse anymore, since we're getting something much better.

**Comment by katzevans** [comment]
I'm not sure if this is still relevant but I bought the game in GOG... and apparently mods are hosted in Steam Workshop..
Is there no workaround for this btw?

**Comment by Dushess** [comment]
Currently one way - dl mods in workshop folder and transfer to your installation

**Comment by spaar** [comment]
@katzevans The in-game mod loader can still load mods from a local directory on your computer (by default still `Besiege_Data/Mods/`).
If some mods you want are only available for download on the Steam workshop, you'd either have to get them from someone else who downloaded them via the workshop, or ask the mod author to provide a download at some other place.

**Comment by katzevans** [comment]
@spaar Thanks for the reply.
Guess there isn't much I can do about that.. Doubt they'd just easily dump a standalone download link for me if I asked nicely but I may as well try. I don't know anyone who owns it on Steam so not much I could do but wait.

@Dushess Well, that's the thing.. I don't own it on Steam so I can't download any of the mods in the workshop.

**Comment by Dushess** [comment]
@katzevans I have one and also use mods, so i can give it to you.

**Comment by katzevans** [comment]
@Dushess You would?
That would be wonderful, thanks!
I've only wanted a few mods:
- EasyScale
- BlockEnhancementMod
- NoBounds
- Return 2 Center (Edit: I forgot this is included in BEM sooo I guess it's not needed?)
I really appreciate you doing this, you can send it to me through email if that's preferable (or any other methods you may prefer)
Email: katz.evanz@gmail.com

**Comment by spaar** [comment]
Closing this, the mod loader will not receive future updates as it was superseded by the official in-game one.
