### ISSUE TITLE
I can't get it to work in-game

### ISSUE THREAD

**Issue by CrimsonDemon357** [spaar/besiege-modloader#66]
sorry about this i don't want to waste your time but I've the downloaded mod loader installer and I've downloaded the latest version of the actual loader and the file is in my besiege steam app folder but whenever i press 'control m' as the video instructs me to do nothing happens I've tried uninstalling and reinstalling, closing besiege and reopening but nothing seems to be working this is probably a minor issue on my part but i couldn't think what else to do about it so I came to you. So please help me

**Comment by spaar** [comment]
See #65. The mod loader does not currently work with the Multiverse update.

**Comment by CrimsonDemon357** [comment]
oh does that mean with the update it doesn't work like at all i thought it just meant in like multiverse levels or level editor, but either way thank you for replying
