### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by vuanhtuan1774** [spaar/besiege-modloader#67]
Hi, i have some issue when install the mod loader, hope u can help me.
I do exacly every thing in the tutorial, even the installer said that the mod is succesfully install, but when i open the game and press Ctrl + M, nothing happen. i tried all the keyboard but nothing happen like in the tutarial video. please help. Thank

**Comment by Dushess** [comment]
Multiverse update? modloader does not support this yet. Use v0.45a or wait.

**Comment by vuanhtuan1774** [comment]
No, its not in multi ver. In normal sanxbox.

**Comment by Dushess** [comment]
Modloader v1.7.1works fine.

**Comment by spaar** [comment]
> No, its not in multi ver. In normal sanxbox.

It doesn't matter whether you just use the normal sandbox, if you are using a version of the game that _has_ the multiverse, the mod loader does not currently work.
The last supported game version v0.45 at the moment.

Take a look at #65 for the current status of the mod loader for multiverse as well as some workarounds.
