### ISSUE TITLE
"Error Downloading Version Information" 

### ISSUE THREAD

**Issue by MarcFaugere** [spaar/besiege-modloader#68]
Because of the new multiverse update, I have had the mod loader installer on my desktop so when I go back into previous build, I can quickly enable all my mods right away. This was working fine until one day I clicked on it and a Error appeared saying "Error downloading version information. Check your internet connection and make sure the installer is allowed access to the internet" It's been like this for 2 weeks now, and I have tried everything i could think of. Anyone know how i can fix this?

**Comment by Bert-Macklin** [comment]
I am trying to install for the first time and am having the same issue.

![bmleer](https://user-images.githubusercontent.com/21964490/36643180-590c0508-1a16-11e8-9bcb-50ebf02064c1.PNG)

**Comment by spaar** [comment]
I'm afraid the installer suddenly has problems connecting to the GitHub API and I'm not sure why. I'm not likely to spend much time investigating this for now as I'd rather get the mod loader for the multiverse option going, so for now, everybody is going to need to use the manual installation method.

Note that you can keep two copies of Besiege around to avoid having to re-install the mod loader all the time which should make this less annoying. See #65 for more information.

**Comment by MarcFaugere** [comment]
Thanks, ill try to keep to versions for now.

**Comment by theblenderanimator** [comment]
Sorry, did not see this.
Though do you have any suggestions on how to fix this?
I’m using besige v0.45a

**Comment by theblenderanimator** [comment]
And how do you use the manual installation,because it appears with the same error

**Comment by MarcFaugere** [comment]
get the mod loader file of the website and replace the file in the besiege
data. You will have to do this every time you change the version of the
game. :(

**Comment by spaar** [comment]
@MarcFaugere As described in #65, it is possible to keep two copies of Besiege, one with the Multiverse update and one old with the mod loader. It's even possible to make both interact with Steam. That way you do not need to reinstall the mod loader all the time.

**Comment by spaar** [comment]
Fixed by #71, I'll make a new build of the installer and upload it now.

**Comment by MarcFaugere** [comment]
Ok thanks
